import type {
  ImageSourcePropType,
} from 'react-native';

export const TAROT_CARD_IMAGES: Record<string, ImageSourcePropType> = {
  ace_of_cups: require('../assets/images/tarot/ace_of_cups.png'),
  ace_of_pentacles: require('../assets/images/tarot/ace_of_pentacles.png'),
  ace_of_swords: require('../assets/images/tarot/ace_of_swords.png'),
  ace_of_wands: require('../assets/images/tarot/ace_of_wands.png'),
  chariot: require('../assets/images/tarot/chariot.png'),
  death: require('../assets/images/tarot/death.png'),
  devil: require('../assets/images/tarot/devil.png'),
  eight_of_cups: require('../assets/images/tarot/eight_of_cups.png'),
  eight_of_pentacles: require('../assets/images/tarot/eight_of_pentacles.png'),
  eight_of_swords: require('../assets/images/tarot/eight_of_swords.png'),
  eight_of_wands: require('../assets/images/tarot/eight_of_wands.png'),
  emperor: require('../assets/images/tarot/emperor.png'),
  empress: require('../assets/images/tarot/empress.png'),
  five_of_cups: require('../assets/images/tarot/five_of_cups.png'),
  five_of_pentacles: require('../assets/images/tarot/five_of_pentacles.png'),
  five_of_swords: require('../assets/images/tarot/five_of_swords.png'),
  five_of_wands: require('../assets/images/tarot/five_of_wands.png'),
  fool: require('../assets/images/tarot/fool.png'),
  four_of_cups: require('../assets/images/tarot/four_of_cups.png'),
  four_of_pentacles: require('../assets/images/tarot/four_of_pentacles.png'),
  four_of_swords: require('../assets/images/tarot/four_of_swords.png'),
  four_of_wands: require('../assets/images/tarot/four_of_wands.png'),
  hanged_man: require('../assets/images/tarot/hanged_man.png'),
  hermit: require('../assets/images/tarot/hermit.png'),
  hierophant: require('../assets/images/tarot/hierophant.png'),
  high_priestess: require('../assets/images/tarot/high_priestess.png'),
  judgement: require('../assets/images/tarot/judgement.png'),
  justice: require('../assets/images/tarot/justice.png'),
  king_of_cups: require('../assets/images/tarot/king_of_cups.png'),
  king_of_pentacles: require('../assets/images/tarot/king_of_pentacles.png'),
  king_of_swords: require('../assets/images/tarot/king_of_swords.png'),
  king_of_wands: require('../assets/images/tarot/king_of_wands.png'),
  knight_of_cups: require('../assets/images/tarot/knight_of_cups.png'),
  knight_of_pentacles: require('../assets/images/tarot/knight_of_pentacles.png'),
  knight_of_swords: require('../assets/images/tarot/knight_of_swords.png'),
  knight_of_wands: require('../assets/images/tarot/knight_of_wands.png'),
  lovers: require('../assets/images/tarot/lovers.png'),
  magician: require('../assets/images/tarot/magician.png'),
  moon: require('../assets/images/tarot/moon.png'),
  nine_of_cups: require('../assets/images/tarot/nine_of_cups.png'),
  nine_of_pentacles: require('../assets/images/tarot/nine_of_pentacles.png'),
  nine_of_swords: require('../assets/images/tarot/nine_of_swords.png'),
  nine_of_wands: require('../assets/images/tarot/nine_of_wands.png'),
  page_of_cups: require('../assets/images/tarot/page_of_cups.png'),
  page_of_pentacles: require('../assets/images/tarot/page_of_pentacles.png'),
  page_of_swords: require('../assets/images/tarot/page_of_swords.png'),
  page_of_wands: require('../assets/images/tarot/page_of_wands.png'),
  queen_of_cups: require('../assets/images/tarot/queen_of_cups.png'),
  queen_of_pentacles: require('../assets/images/tarot/queen_of_pentacles.png'),
  queen_of_swords: require('../assets/images/tarot/queen_of_swords.png'),
  queen_of_wands: require('../assets/images/tarot/queen_of_wands.png'),
  seven_of_cups: require('../assets/images/tarot/seven_of_cups.png'),
  seven_of_pentacles: require('../assets/images/tarot/seven_of_pentacles.png'),
  seven_of_swords: require('../assets/images/tarot/seven_of_swords.png'),
  seven_of_wands: require('../assets/images/tarot/seven_of_wands.png'),
  six_of_cups: require('../assets/images/tarot/six_of_cups.png'),
  six_of_pentacles: require('../assets/images/tarot/six_of_pentacles.png'),
  six_of_swords: require('../assets/images/tarot/six_of_swords.png'),
  six_of_wands: require('../assets/images/tarot/six_of_wands.png'),
  star: require('../assets/images/tarot/star.png'),
  strength: require('../assets/images/tarot/strength.png'),
  sun: require('../assets/images/tarot/sun.png'),
  temperance: require('../assets/images/tarot/temperance.png'),
  ten_of_cups: require('../assets/images/tarot/ten_of_cups.png'),
  ten_of_pentacles: require('../assets/images/tarot/ten_of_pentacles.png'),
  ten_of_swords: require('../assets/images/tarot/ten_of_swords.png'),
  ten_of_wands: require('../assets/images/tarot/ten_of_wands.png'),
  three_of_cups: require('../assets/images/tarot/three_of_cups.png'),
  three_of_pentacles: require('../assets/images/tarot/three_of_pentacles.png'),
  three_of_swords: require('../assets/images/tarot/three_of_swords.png'),
  three_of_wands: require('../assets/images/tarot/three_of_wands.png'),
  tower: require('../assets/images/tarot/tower.png'),
  two_of_cups: require('../assets/images/tarot/two_of_cups.png'),
  two_of_pentacles: require('../assets/images/tarot/two_of_pentacles.png'),
  two_of_swords: require('../assets/images/tarot/two_of_swords.png'),
  two_of_wands: require('../assets/images/tarot/two_of_wands.png'),
  wheel_of_fortune: require('../assets/images/tarot/wheel_of_fortune.png'),
  world: require('../assets/images/tarot/world.png'),
};

const TAROT_ALIASES: Record<string, string> = {
  "ace_cup": "ace_of_cups",
  "ace_cups": "ace_of_cups",
  "ace_of_cup": "ace_of_cups",
  "ace_of_pentacle": "ace_of_pentacles",
  "ace_of_sword": "ace_of_swords",
  "ace_of_wand": "ace_of_wands",
  "ace_pentacle": "ace_of_pentacles",
  "ace_pentacles": "ace_of_pentacles",
  "ace_sword": "ace_of_swords",
  "ace_swords": "ace_of_swords",
  "ace_wand": "ace_of_wands",
  "ace_wands": "ace_of_wands",
  "cups_ace": "ace_of_cups",
  "cups_eight": "eight_of_cups",
  "cups_five": "five_of_cups",
  "cups_four": "four_of_cups",
  "cups_king": "king_of_cups",
  "cups_knight": "knight_of_cups",
  "cups_nine": "nine_of_cups",
  "cups_page": "page_of_cups",
  "cups_queen": "queen_of_cups",
  "cups_seven": "seven_of_cups",
  "cups_six": "six_of_cups",
  "cups_ten": "ten_of_cups",
  "cups_three": "three_of_cups",
  "cups_two": "two_of_cups",
  "eight_cup": "eight_of_cups",
  "eight_cups": "eight_of_cups",
  "eight_of_cup": "eight_of_cups",
  "eight_of_pentacle": "eight_of_pentacles",
  "eight_of_sword": "eight_of_swords",
  "eight_of_wand": "eight_of_wands",
  "eight_pentacle": "eight_of_pentacles",
  "eight_pentacles": "eight_of_pentacles",
  "eight_sword": "eight_of_swords",
  "eight_swords": "eight_of_swords",
  "eight_wand": "eight_of_wands",
  "eight_wands": "eight_of_wands",
  "five_cup": "five_of_cups",
  "five_cups": "five_of_cups",
  "five_of_cup": "five_of_cups",
  "five_of_pentacle": "five_of_pentacles",
  "five_of_sword": "five_of_swords",
  "five_of_wand": "five_of_wands",
  "five_pentacle": "five_of_pentacles",
  "five_pentacles": "five_of_pentacles",
  "five_sword": "five_of_swords",
  "five_swords": "five_of_swords",
  "five_wand": "five_of_wands",
  "five_wands": "five_of_wands",
  "four_cup": "four_of_cups",
  "four_cups": "four_of_cups",
  "four_of_cup": "four_of_cups",
  "four_of_pentacle": "four_of_pentacles",
  "four_of_sword": "four_of_swords",
  "four_of_wand": "four_of_wands",
  "four_pentacle": "four_of_pentacles",
  "four_pentacles": "four_of_pentacles",
  "four_sword": "four_of_swords",
  "four_swords": "four_of_swords",
  "four_wand": "four_of_wands",
  "four_wands": "four_of_wands",
  "hanged": "hanged_man",
  "judgment": "judgement",
  "king_cup": "king_of_cups",
  "king_cups": "king_of_cups",
  "king_of_cup": "king_of_cups",
  "king_of_pentacle": "king_of_pentacles",
  "king_of_sword": "king_of_swords",
  "king_of_wand": "king_of_wands",
  "king_pentacle": "king_of_pentacles",
  "king_pentacles": "king_of_pentacles",
  "king_sword": "king_of_swords",
  "king_swords": "king_of_swords",
  "king_wand": "king_of_wands",
  "king_wands": "king_of_wands",
  "knight_cup": "knight_of_cups",
  "knight_cups": "knight_of_cups",
  "knight_of_cup": "knight_of_cups",
  "knight_of_pentacle": "knight_of_pentacles",
  "knight_of_sword": "knight_of_swords",
  "knight_of_wand": "knight_of_wands",
  "knight_pentacle": "knight_of_pentacles",
  "knight_pentacles": "knight_of_pentacles",
  "knight_sword": "knight_of_swords",
  "knight_swords": "knight_of_swords",
  "knight_wand": "knight_of_wands",
  "knight_wands": "knight_of_wands",
  "nine_cup": "nine_of_cups",
  "nine_cups": "nine_of_cups",
  "nine_of_cup": "nine_of_cups",
  "nine_of_pentacle": "nine_of_pentacles",
  "nine_of_sword": "nine_of_swords",
  "nine_of_wand": "nine_of_wands",
  "nine_pentacle": "nine_of_pentacles",
  "nine_pentacles": "nine_of_pentacles",
  "nine_sword": "nine_of_swords",
  "nine_swords": "nine_of_swords",
  "nine_wand": "nine_of_wands",
  "nine_wands": "nine_of_wands",
  "page_cup": "page_of_cups",
  "page_cups": "page_of_cups",
  "page_of_cup": "page_of_cups",
  "page_of_pentacle": "page_of_pentacles",
  "page_of_sword": "page_of_swords",
  "page_of_wand": "page_of_wands",
  "page_pentacle": "page_of_pentacles",
  "page_pentacles": "page_of_pentacles",
  "page_sword": "page_of_swords",
  "page_swords": "page_of_swords",
  "page_wand": "page_of_wands",
  "page_wands": "page_of_wands",
  "pentacles_ace": "ace_of_pentacles",
  "pentacles_eight": "eight_of_pentacles",
  "pentacles_five": "five_of_pentacles",
  "pentacles_four": "four_of_pentacles",
  "pentacles_king": "king_of_pentacles",
  "pentacles_knight": "knight_of_pentacles",
  "pentacles_nine": "nine_of_pentacles",
  "pentacles_page": "page_of_pentacles",
  "pentacles_queen": "queen_of_pentacles",
  "pentacles_seven": "seven_of_pentacles",
  "pentacles_six": "six_of_pentacles",
  "pentacles_ten": "ten_of_pentacles",
  "pentacles_three": "three_of_pentacles",
  "pentacles_two": "two_of_pentacles",
  "queen_cup": "queen_of_cups",
  "queen_cups": "queen_of_cups",
  "queen_of_cup": "queen_of_cups",
  "queen_of_pentacle": "queen_of_pentacles",
  "queen_of_sword": "queen_of_swords",
  "queen_of_wand": "queen_of_wands",
  "queen_pentacle": "queen_of_pentacles",
  "queen_pentacles": "queen_of_pentacles",
  "queen_sword": "queen_of_swords",
  "queen_swords": "queen_of_swords",
  "queen_wand": "queen_of_wands",
  "queen_wands": "queen_of_wands",
  "seven_cup": "seven_of_cups",
  "seven_cups": "seven_of_cups",
  "seven_of_cup": "seven_of_cups",
  "seven_of_pentacle": "seven_of_pentacles",
  "seven_of_sword": "seven_of_swords",
  "seven_of_wand": "seven_of_wands",
  "seven_pentacle": "seven_of_pentacles",
  "seven_pentacles": "seven_of_pentacles",
  "seven_sword": "seven_of_swords",
  "seven_swords": "seven_of_swords",
  "seven_wand": "seven_of_wands",
  "seven_wands": "seven_of_wands",
  "six_cup": "six_of_cups",
  "six_cups": "six_of_cups",
  "six_of_cup": "six_of_cups",
  "six_of_pentacle": "six_of_pentacles",
  "six_of_sword": "six_of_swords",
  "six_of_wand": "six_of_wands",
  "six_pentacle": "six_of_pentacles",
  "six_pentacles": "six_of_pentacles",
  "six_sword": "six_of_swords",
  "six_swords": "six_of_swords",
  "six_wand": "six_of_wands",
  "six_wands": "six_of_wands",
  "swords_ace": "ace_of_swords",
  "swords_eight": "eight_of_swords",
  "swords_five": "five_of_swords",
  "swords_four": "four_of_swords",
  "swords_king": "king_of_swords",
  "swords_knight": "knight_of_swords",
  "swords_nine": "nine_of_swords",
  "swords_page": "page_of_swords",
  "swords_queen": "queen_of_swords",
  "swords_seven": "seven_of_swords",
  "swords_six": "six_of_swords",
  "swords_ten": "ten_of_swords",
  "swords_three": "three_of_swords",
  "swords_two": "two_of_swords",
  "ten_cup": "ten_of_cups",
  "ten_cups": "ten_of_cups",
  "ten_of_cup": "ten_of_cups",
  "ten_of_pentacle": "ten_of_pentacles",
  "ten_of_sword": "ten_of_swords",
  "ten_of_wand": "ten_of_wands",
  "ten_pentacle": "ten_of_pentacles",
  "ten_pentacles": "ten_of_pentacles",
  "ten_sword": "ten_of_swords",
  "ten_swords": "ten_of_swords",
  "ten_wand": "ten_of_wands",
  "ten_wands": "ten_of_wands",
  "the_chariot": "chariot",
  "the_devil": "devil",
  "the_emperor": "emperor",
  "the_empress": "empress",
  "the_fool": "fool",
  "the_hanged_man": "hanged_man",
  "the_hermit": "hermit",
  "the_hierophant": "hierophant",
  "the_lovers": "lovers",
  "the_magician": "magician",
  "the_moon": "moon",
  "the_star": "star",
  "the_sun": "sun",
  "the_tower": "tower",
  "the_world": "world",
  "three_cup": "three_of_cups",
  "three_cups": "three_of_cups",
  "three_of_cup": "three_of_cups",
  "three_of_pentacle": "three_of_pentacles",
  "three_of_sword": "three_of_swords",
  "three_of_wand": "three_of_wands",
  "three_pentacle": "three_of_pentacles",
  "three_pentacles": "three_of_pentacles",
  "three_sword": "three_of_swords",
  "three_swords": "three_of_swords",
  "three_wand": "three_of_wands",
  "three_wands": "three_of_wands",
  "two_cup": "two_of_cups",
  "two_cups": "two_of_cups",
  "two_of_cup": "two_of_cups",
  "two_of_pentacle": "two_of_pentacles",
  "two_of_sword": "two_of_swords",
  "two_of_wand": "two_of_wands",
  "two_pentacle": "two_of_pentacles",
  "two_pentacles": "two_of_pentacles",
  "two_sword": "two_of_swords",
  "two_swords": "two_of_swords",
  "two_wand": "two_of_wands",
  "two_wands": "two_of_wands",
  "wands_ace": "ace_of_wands",
  "wands_eight": "eight_of_wands",
  "wands_five": "five_of_wands",
  "wands_four": "four_of_wands",
  "wands_king": "king_of_wands",
  "wands_knight": "knight_of_wands",
  "wands_nine": "nine_of_wands",
  "wands_page": "page_of_wands",
  "wands_queen": "queen_of_wands",
  "wands_seven": "seven_of_wands",
  "wands_six": "six_of_wands",
  "wands_ten": "ten_of_wands",
  "wands_three": "three_of_wands",
  "wands_two": "two_of_wands",
  "wheel": "wheel_of_fortune",
  "wheel_fortune": "wheel_of_fortune",
};

export function normalizeTarotCardId(
  value?: string,
): string {
  return String(value ?? '')
    .trim()
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/^the\s+/g, 'the_')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

export function getTarotCardImage(
  cardIdOrName?: string,
  fallbackName?: string,
): ImageSourcePropType | undefined {
  const candidates = [
    cardIdOrName,
    fallbackName,
  ];

  for (const candidate of candidates) {
    const normalized =
      normalizeTarotCardId(candidate);

    const direct =
      TAROT_CARD_IMAGES[normalized];

    if (direct) {
      return direct;
    }

    const withoutThe =
      normalized.replace(/^the_/, '');

    const noTheImage =
      TAROT_CARD_IMAGES[withoutThe];

    if (noTheImage) {
      return noTheImage;
    }

    const alias =
      TAROT_ALIASES[normalized] ??
      TAROT_ALIASES[withoutThe];

    if (
      alias &&
      TAROT_CARD_IMAGES[alias]
    ) {
      return TAROT_CARD_IMAGES[alias];
    }
  }

  return undefined;
}
